Add a --system argument for system-wide installation
kynan/nbstripout pull request #149
Opened 2021-04-15 10:07 UTC by PLPeeters

This PR adds a `--system` argument for system-wide installation.

Since there doesn't seem to be a simple way to figure out the `$(prefix)` variable of the Git installation, I had to resort to a kind of hacky way to figure that one out in order to put the system-wide `gitattributes` file in the correct place (see the `_get_system_gitconfig_folder()` function).

I also fixed the path of the gitattributes file in the documentation when using the `--global` argument, which was incorrectly documented as being `.git/info/attributes` instead of `~/.config/git/attributes`.

I also took the liberty of adding a few newlines to improve readability.

2021-04-15 10:44 UTC, PLPeeters commented
I also just went ahead and added a fix and a test for the `--status` command which was apparently broken, along with some unification in the treatment of shell output (setting `text=True` everywhere and removing calls to `.decode()` that are no longer necessary with this). I can do a separate PR for that if you prefer, but since it intersects with my changes it was just easier for me to include it in here.

2021-04-15 21:39 UTC, kynan requested changes
Thanks for your contribution! That's a useful feature.

Thanks also for the other fixes  / cleanup and for adding a test.

Just a minor nit, otherwise I think this is good to go!

2021-04-15 21:39 UTC, kynan commented on README.rst
> +    nbstripout --install --system
In most cases you'd probably need to run this with `sudo`. Worth a note?

2021-04-15 21:39 UTC, kynan commented on nbstripout/_nbstripout.py
> +    except CalledProcessError as e:
What are some possible conditions where this call would fail? And what's the content of the error message?

2021-04-15 21:39 UTC, kynan commented on nbstripout/_nbstripout.py
> +            print('Did you forget to sudo?')
Write to stderr

2021-04-21 07:34 UTC, PLPeeters commented on nbstripout/_nbstripout.py
> +    except CalledProcessError as e:
Do you mean the cases where we would enter the `except` block? If so, the call fails if the config file does not exist, but when it does it prints the path where it expected to find it, which is why I parse the output to get the path.

2021-04-21 22:57 UTC, kynan approved these changes
Thanks, I think this is good to go now!

2021-04-21 23:08 UTC, kynan requested changes
Sorry, spoke too soon, [this is not passing tests](https://travis-ci.org/github/kynan/nbstripout/builds/767845555):
1. looks like the `text` parameter to `check_output` is 3.7+ only. Can you use `universal_newlines` instead?
2. we're getting [lots of stray output](https://travis-ci.org/github/kynan/nbstripout/jobs/767845558): `fatal: --local can only be used inside a git repository`

2021-04-22 08:13 UTC, PLPeeters commented
@kynan Changed the text parameter as requested.

The stray output was due to the `git config` call to fetch the extra keys. I changed it to a simple `git config` when `nbstripout` is called without the `--system` or `--global` parameters, since that seemed to make the most sense.

I also fixed the Git test since it didn't run properly on my system even though it looks fine on Travis. Apparently the version of Git on macOS seems to insist on having a newline at the end of the attributes file (it threw an `*.txt is not a valid attribute name: .git/info/attributes:1` error on all the Git calls in that test for me).

2021-04-24 07:07 UTC, kynan approved these changes
Thanks, excellent work, really appreciate your contribution :)

2021-04-24 07:07 UTC, merged