Add support for stripping init cells
kynan/nbstripout pull request #157
Opened 2021-09-14 11:29 UTC by Pugio

As mentioned in #156 :

This PR adds a flag: `--strip-init-cells` which alters the current behavior to also remove outputs from init cells.

Reason:
I have a whole bunch of notebooks which have the `init_cell: true` metadata. This generates a nice default set of UI widgets as soon as the notebook is loaded. However, since this is generated automatically, I don't want all the widget output checked into my source repo. Right now, every time a user commits a change to the notebook, we have huge amounts of cell output from the init_cell cells.

2021-09-19 05:55 UTC, kynan requested changes

2021-09-19 05:55 UTC, kynan commented on nbstripout/_nbstripout.py
> +                                    args.strip_empty_cells, args.strip_init_cells, _parse_size(args.max_size))
```suggestion
            nb = strip_output(nb, args.keep_output, args.keep_count, extra_keys, 
                              args.strip_empty_cells, args.strip_init_cells, _parse_size(args.max_size))
```

2021-09-19 05:55 UTC, kynan commented on nbstripout/_nbstripout.py
> +                                    args.strip_empty_cells, args.strip_init_cells, _parse_size(args.max_size))
Please fix indentation

2021-09-19 06:00 UTC, kynan commented
For some reason CI hasn't run on this PR. Investigating what's happened there.

2021-09-19 06:20 UTC, kynan commented
My bad, I hadn't configured GitHub Actions to run on a PR. I had to push a dummy commit to your branch to trigger CI.

2021-09-19 06:21 UTC, kynan requested changes
Please address the test failures and add a new test for your feature.

2021-09-20 02:46 UTC, Pugio commented
Thank you. I have fixed the tests, and added a new one for the new case.

2021-09-20 20:27 UTC, kynan approved these changes
Thanks for your contribution, this looks good to go!

2021-09-20 20:27 UTC, merged