Add an --strip-tag-cells="some tags" Option
kynan/nbstripout pull request #161
Opened 2021-11-18 12:48 UTC by boun

Hi, 

the present pull request adds an apparatus to skip entire cells based on a list of tags that can be passed as command line argument.

It might be unappropriate to suggest such a feature to a tool, that indicates in its name that it strips output only. Having said that, there is already an option that strips empty cells entirely. Therefore I leave the decision up to you :)

My use case is, that I create lots of exercise notebooks for students. Clearing the solution is manual and error-prone labor. With this patch applied a simple makefile can convert solutions to exercises and (unrelated to this tool) convert solutions to a pdf.

Tests pass an I added an additional one.

2021-11-18 12:50 UTC, boun commented on nbstripout/_nbstripout.py
> -            nb = strip_output(nb, args.keep_output, args.keep_count, extra_keys, args.strip_empty_cells, _parse_size(args.max_size))
BTW: The args.strip_init_cells option is missing in the original code. I followed alone that line.

2022-01-02 20:25 UTC, kynan requested changes
Please rebase your branch on master.

2022-01-02 20:25 UTC, kynan commented on README.rst
> +    nbstripout --strip-tag-cells="soltion"
typo: "solution"

2022-01-02 20:25 UTC, kynan commented on nbstripout/_nbstripout.py
> +    parser.add_argument('--strip-tag-cells', default='',
I have a mild preference for `--strip-tagged-cells` as that reads more like a sentence fragment.

2022-01-02 20:25 UTC, kynan commented on nbstripout/_nbstripout.py
> +    parser.add_argument('--strip-tag-cells', default='',
Actually, let's call this `--drop-tagged-cells`: the term "stripping" is mostly used in the sense of "strip output from a cell".

2022-01-02 20:25 UTC, kynan commented on nbstripout/_nbstripout.py
> -            nb = strip_output(nb, args.keep_output, args.keep_count, extra_keys, args.strip_empty_cells, _parse_size(args.max_size))
That's an oversight, thanks for spotting! I've fixed this in ea31172

2022-01-02 20:25 UTC, kynan commented on nbstripout/_nbstripout.py
> +                              args.strip_tag_cells.split(" "),
```suggestion
                              args.strip_tag_cells.split(),
```

2022-01-02 20:25 UTC, kynan commented on nbstripout/_nbstripout.py
> +                              args.strip_tag_cells.split(" "),
```suggestion
                              args.strip_tag_cells.split(),
```

2022-01-02 20:25 UTC, kynan commented on nbstripout/_utils.py
> -def _cells(nb, conditional=None):
Given this is only called from a single place, maybe drop the default value, as it's always passed.

2022-01-02 20:25 UTC, kynan commented on nbstripout/_utils.py
> +            if conditionals:
That check is redundant: iterating an empty list will do the right thing.

2022-01-02 20:25 UTC, kynan commented on nbstripout/_utils.py
> +        if conditionals:
Ditto

2022-01-03 21:54 UTC, boun commented
Hi,

thanks for the review! I was unaware that `strip()` can be used without argument. Again what learned! Changes followed your requests. One thing that I noticed is that one additional (?) test is failing unrelated to my changes (well, I *think* I did not break it). 

```
platform darwin -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0

...

FAILED nbstripout/_nbstripout.py::FLAKE8 - AttributeError: '_io.StringIO' object has no attribute 'buffer'
```

2022-01-16 21:24 UTC, kynan requested changes
I think this is looking mostly good know, just a minor formatting inconsistency.

2022-01-16 21:24 UTC, kynan commented on nbstripout/_nbstripout.py
> +                              args.strip_init_cells, _parse_size(args.max_size))
```suggestion
            nb = strip_output(nb, args.keep_output, args.keep_count, extra_keys, args.drop_empty_cells,
                              args.drop_tagged_cells.split(), args.strip_init_cells, _parse_size(args.max_size))
```

2022-01-16 21:24 UTC, kynan commented on nbstripout/_nbstripout.py
> +                              _parse_size(args.max_size))
```suggestion
            nb = strip_output(nb, args.keep_output, args.keep_count, extra_keys, args.drop_empty_cells,
                              args.drop_tagged_cells.split(), args.strip_init_cells, _parse_size(args.max_size))
```

2022-01-16 21:37 UTC, kynan commented
Btw. the test failure is tholo/pytest-flake8#81 and unrelated to your changes. I've attempted to force flake8 to version 3.9.2 in aa7dad1. Can you rebase on master again?

2022-01-17 18:53 UTC, kynan approved these changes
Thanks for your contribution!

2022-01-17 18:54 UTC, merged