Replace sys.exit() with raise SystemExit
kynan/nbstripout pull request #173
Opened 2022-10-02 14:08 UTC by janosh

Reasoning explained in https://youtu.be/ZbeSPc5wL0g.

Split-out PR following https://github.com/kynan/nbstripout/pull/169#discussion_r985213917.

2022-10-08 12:44 UTC, kynan requested changes
Realised that we shouldn't be exiting from within functions but simply return.

2022-10-08 12:44 UTC, kynan commented on nbstripout/_nbstripout.py
> +        raise SystemExit(1)
```suggestion
        return 1
```

2022-10-08 12:44 UTC, kynan commented on nbstripout/_nbstripout.py
> +        raise SystemExit(1)
```suggestion
        return 1
```

2022-10-08 12:44 UTC, kynan commented on nbstripout/_nbstripout.py
> +        raise SystemExit(1)
```suggestion
        return 1
```

2022-10-08 12:44 UTC, kynan commented on nbstripout/_nbstripout.py
> +        raise SystemExit(1)
```suggestion
        return 1
```

2022-10-08 12:44 UTC, kynan commented on nbstripout/_nbstripout.py
> +        raise SystemExit(1)
```suggestion
        return 1
```

2022-10-08 15:43 UTC, janosh commented
> Realised that we shouldn't be exiting from within functions but simply return.

Was thinking about raising that point too.

2022-10-09 15:35 UTC, kynan approved these changes

2022-10-09 15:35 UTC, merged