Draft: Fix Testing by stripping out Cram
kynan/nbstripout pull request #176
Opened 2022-11-13 00:12 UTC by arobrien

[Cram](https://github.com/brodie/cram) is abandoned (last release in 2016, and repository is now archived), so the currently broken tests on Windows will never get fixed if we stick with Cram. #38 

I believe that the best way forward is to migrate away from Cram. I looked at a few potential alternative pytest plugins, but it seems like we can just make use of subprocess ourselves.
I have created `test_end_to_end.py` and started migrating simple "Run nbstripout and compare the output" tests to that.
Testing diffs, installers, and status will be a little harder, but I still think will be similar.
I'll keep this PR in draft until I've brought all of these across.

In the long term it would probably be better to create a more testable program structure to test much of this, but I don't propose to do that in this PR.

2022-11-13 02:19 UTC, arobrien commented
I've moved all of the simple "run nbstripout and check the output" tests, and the tests are all passing on my fork (I'm using a Dummy PR to trigger them).

I'm having a look at diff and installation/status scripts now.

2022-11-13 09:07 UTC, arobrien commented
I'm happy with how most of this has worked out for the end-to-end tests, and even testing the diff command, but the installation/status test scripts are turning out very messy when I try and port them over.

I think that leaving those as cram for now, even if they can't run on windows, is probably best. I'll try and implement a couple of very basic tests of the install functionality to complement them.

2022-11-13 09:53 UTC, arobrien commented
I've given up on porting the diff and install/status scripts. We now have a lot more tests running on Windows, I'm calling that a win for this PR.

2022-11-13 19:40 UTC, kynan requested changes
Thanks for doing this! Definitely an improvement :) I think this is good to go pending a minor nit.

2022-11-13 19:40 UTC, kynan commented on tests/requirements.txt
> +pytest-cram == 0.2.2
Trailing whitespace, please revert

2022-11-13 23:00 UTC, arobrien commented on tests/requirements.txt
> +pytest-cram == 0.2.2
👍

2022-11-14 17:57 UTC, kynan approved these changes
Thanks! This is now good to go :)

2022-11-14 18:01 UTC, merged