Update README.md with git-filter-repo
kynan/nbstripout pull request #194
Opened 2024-02-17 16:08 UTC by LunarLanding

Did the minimal changes to the lint-history example on git-filter-repo to allow using nbstripout while keeping performance by never spawning a second interpreter.
See https://github.com/kynan/nbstripout/issues/193

2024-03-17 08:50 UTC, kynan requested changes
Thanks for this comprehensive example! Just a few nits :)

2024-03-17 08:50 UTC, kynan commented on README.md
> +operates on all ipynb-files in the repo: :
```suggestion
[`git filter-repo`](https://github.com/newren/git-filter-repo) to strip output
from existing notebooks. This invocation operates on all ipynb files in the repo:
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +    import json,warnings,nbformat
```suggestion
    import json, warnings, nbformat
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +            notebook = nbformat.reads(blob.data,as_version=nbformat.NO_CONVERT)
```suggestion
            notebook = nbformat.reads(blob.data, as_version=nbformat.NO_CONVERT)
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +        strip_output(notebook, keep_output=False, keep_count=False, keep_id=False, extra_keys=["metadata.widgets","metadata.execution","cell.attachments"], drop_empty_cells=True, drop_tagged_cells=[]
```suggestion
        strip_output(notebook, keep_output=False, keep_count=False, keep_id=False, extra_keys=["metadata.widgets","metadata.execution","cell.attachments"], drop_empty_cells=True,  drop_tagged_cells=[],strip_init_cells=False, max_size=0)
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +        old_len=len(blob.data)
```suggestion
        old_len = len(blob.data)
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +            print(change.blob_id,change.filename,old_len,len(blob.data))
```suggestion
        if old_len != len(blob.data):
            print(change.blob_id, change.filename, old_len, len(blob.data))
```

2024-03-17 08:50 UTC, kynan commented on README.md
> +         print("ERROR",type(exc),change.blob_id,filename)
```suggestion
    except NotJSONError as e:
         print("ERROR", type(e), change.blob_id, filename)
```

2024-03-17 12:07 UTC, LunarLanding commented
Ahh, my bad, did not see the 'add suggestion to batch' option.

2024-03-23 18:21 UTC, kynan approved these changes
Thanks! This is good to go now 🙂  No worries about the many commits, I'll squash them anyway.

2024-03-23 18:22 UTC, merged